### ISSUE TITLE
Per address limit flexibility

### ISSUE THREAD

**Issue by jhernandezb** [public-awesome/launchpad#164]
Allow the minter creator 2 different types  of how the limit is applied  `Combined|Split`

**Combined:** Will keep the counter across whitelist and public mint
**Split**: Whitelist and Public Mint counter will be considered as different (resets after WL)

**Comment by yubrew** [comment]
I think it's better to use one policy and stick to it. In this case, keep it as combined. Consider another feature that we will support soon is multiple whitelists.

**Comment by shanev** [comment]
I'm also leaning towards keeping it one way, though I think the split approach is more intuitive and will lead to less code bugs because there's less shared state.

**Comment by yubrew** [comment]
this issue is stale. closing unless a lot of creators ask about this again
