### ISSUE TITLE
add sg721-updatable

### ISSUE THREAD

**Issue by yubrew** [public-awesome/launchpad#349]
update and freeze

**Comment by ivmidable** [comment]
I have something similar at https://github.com/ivmidable/sg721-mutable. I'm personally torn over if there should be a freeze function. sg721-base should probably implement the migrate entry point as I feel like it would be better to have people migrate from sg721-base to sg721-mutable/updatable, make the changes they need and then migrate back to base. that way the collection is frozen again but if something else needs fixing/updating they could migrate back.

**Comment by yubrew** [comment]
just needs review, and gov proposal

**Comment by yubrew** [comment]
**refactor to use base_token_uri**
